### ISSUE TITLE
I am getting ERROR : DaggerSetupComponent does not exist

### ISSUE THREAD

**Issue by msvidal2** [aws-samples/amazon-qldb-double-entry-sample-java#3]
![image](https://user-images.githubusercontent.com/56450223/87228843-4805fd80-c37a-11ea-8607-6546cf3b5501.png)

**Comment by aurghob33** [comment]
Hi @msvidal2,
Thanks for pointing this out!
We had assumed that the user would build and then try running the task.
The build generates the required files and should fix the issue.
Based on this issue, In https://github.com/aws-samples/amazon-qldb-double-entry-sample-java/pull/4, we have added an instruction to build as well in our README.
Does running the build (./gradlew build) and then running the tasks according to the README help ?

**Comment by ghost** [comment]
Hi @aurghob33 

Ok. Thanks for you help

**Comment by aurghob33** [comment]
Hi @msvidal2 ,
Were you able to move forward?
If yes, I'll be closing this issue

**Comment by AyaZhang** [comment]
I had the same errors after running `./gradlew build`
The real issue is this line: 
`Error:java: java.lang.NoClassDefFoundError: javax/annotation/Generated`

The error went away after I switched to Java 8

ref: https://stackoverflow.com/questions/48238014/how-can-be-solved-java-lang-noclassdeffounderror-javax-annotation-generated
